name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
api-version: 1.17
loadbefore:
  - ClaimChunk
depend:
  - ClaimChunk
authors:
  - Twosquirrels
description: ${project.description}
website: ${project.url}#readme
